### ISSUE TITLE
Pridėti naują klasifikatorių šeima

### ISSUE THREAD

**Issue by ambrazasp** [AplinkosMinisterija/biip-gyvunai-api#10]
Pridėti naują klasifikatorių pavadinimu **Šeima**, laukai: 
- [x] Pavadinimas
- [x] Lotyniškas pavadinimas
- [x] Neleisti įvesti naujos šeimos, jei sutampa ir LT ir LOT. pavadinimas.

![Image](https://github.com/user-attachments/assets/ab2d64c6-4aa2-4cec-9e1a-63dc19646937)

![Image](https://github.com/user-attachments/assets/9fda7aa9-6996-467f-965e-d0b404d7ac49)

**Comment by IngaPauliuniene** [comment]
Reikia pataisyti tikrinimus:

Jei lt pavadinimas yra pvz **Acroporidae** ir lot pavadinimas **Acroporidae**, tuomet turi leisti užsaugoti. Nes yra tokių šeimų ir rūšių kai jie nežino lietuviško pavadinimo. 

Tačiau reikia neleisti į sistemą įvesti **pasikartojančių**. Pvz jei jau sąraše yra įvesta:

Baliniai vėžliai	Emydidae

Tai man vėl vedant **Baliniai vėžliai	Emydidae** turi rodyti klaidą - tokia šeima jau egzistuoja. tai yra jei jau buvo įvestas su tokiu pačiu lt ir lot pavadinimu dar kartą neleistų įvesti.

Bet jei vedu Balinis vėžlys  Emydidae arba Baliniai vėžliai ALydidae - tuomet leistų įvesti. Tai yra jei skiriasi bent kuris pavadinimas ar lt ar lot, tuomet leistų įvesti.

Jei neaišku galime susiskambinti.
